using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
// Note: Most assembly attributes are now generated from the project file PropertyGroup
// Only keeping attributes that are not auto-generated by the SDK

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typeRevit.Lib if this project is exposed to COM
[assembly: Guid("04b918ec-6956-4fd9-ac34-1018929b7763")]